version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - '5432:5432'
    restart: always

  backend:
    image: aleksander777888/foodgarm_backend:latest
    volumes:
      - ../static/:/app/static/
      - ../media/:/app/media/recipes/
    depends_on:
      - db
    env_file:
      - ./.env
    restart: always

  frontend:
    image: aleksander777888/foodgarm_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - ../static/:/var/html/static/
      - ../media/:/var/html/media/recipes/

volumes:
  static_value:
  media_value:
  postgres_data: