# Generated by Django 3.2.13 on 2022-10-06 12:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_rename_description_recipe_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='сooking_time',
        ),
        migrations.AddField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Время приготовления  не менее 1 минуты!')], verbose_name='Время приготовления'),
            preserve_default=False,
        ),
    ]
